### ISSUE TITLE
[Future Update Ideas] Anvil Rework

### ISSUE THREAD

**Issue by Mowmaster** [Mowmaster/Pedestals#114]
The xp anvil is known to be very good, with little limits on how crazy your enchants can get (when unlocked)
but its time to dial it back to a more balanced state.

Currently i feel the 105 default xp level cap on the anvil is sufficient, as it requires players to consider if they want 1 very high levels enchant, or a few decent enchants, or a lot of low leveled enchants on gear.
(thanks to using rarity as a multiplier for cost basically)

I think for starters, some tools to help see what enchants traits are would be handy, 
maybe an analyser tool that can tell you the details about an item with enchants?

the anvil should have a rarity cap, based off that items enchantability, so it can still do combining of enchants that normally wouldnt work together, but your capped by the total rarity on the item. so there is a hard limit on how many really good enchants. Also possibly a treasure limit based on maybe an upgrade item in pedestals? like 1 by default, but maybe some special items to increase that limit???

also some sort of level up system for items? so that over their use you can add more enchants to them, so that you build up use experience in the tool, and you use that up when over combining enchants, but add some sort of instability the higher you go, and eventually something that is a constant drain. and when your 'required use experience' is above the' current used experience', the player may experience different negative effects. like
- Slowness
- Mining fatigue
- Blindness?
- Nausiea?
- negative health?
- hunger

then maybe once the use experience hits 0 a curse will be applied to the tool, which will reduce the use cost of it, and give a slight bump to the uses just to that it wont drain itself again and repeatingly add more curses...

**Comment by Mowmaster** [comment]
I also had another idea regarding the actual process for combining over leveled enchants, 
Having played a bit of Genshin Impact, i took a liking to their tool Ascend system, where you need inworld collectables + mob loot drops + dungeon loot drops + money to level up tools. 
Ithink some additonal cost on top of xp(money)/diamonds(in world collectable) should be used.
Maybe setup some tables of enchants that require special items to over level them (recipes?) then require more and more of those items as the over level increases? 
Also would need to rework the anvil to allow for more pedestals to be used. 
maybe use the corners too? or do some sort of infusion like setup???

**Comment by MuteTiefling** [comment]
Regarding XP as fuel: I like this, but I'd temper it back a bit. Having negative effects like nausea can be exceptionally annoying (looking at you Blood Magic). As a player, I'd much rather have something simply stop working, rather than actively annoy me. 

So, let's say that an ability would be that a weapon summons lightning sparks that spread out and arc from mob to mob (think diablo 2). This could have a high level of XP cost per proc and once you're out of XP, well you're just back to a regular sword. 

For levelling up tools/abilities, exploration is <3. Finding things in world is 100% better than crafting table whack-o-mole, as long as these things can be considered extras. If I have to go out and find X item to make a component for a pedestal that's a bit... less interesting as a base mechanic. Leave that stuff for Expert packs. But as long as I'm just stumbling across nifty things I can add to my gear to improve them over time, that keeps exploration valuable for a long time in game. The tool grows with you and you're rewarded for continuously working on it. 

A lossy method of transferring power ups from one set of gear to another would also be quite nice. So you can start powering up early, but you don't lose 100% of your progress if you decide to move from iron to diamond gear, for example. Doesn't have to be a harsh penalty. Maybe a 10% loss of effectiveness overall. And the possibility to negate the loss entirely with a semi-rare item to focus the transfer. 

Are you considering making your own structures that would allow people to hunt for and find the loot? 

Kinda starting to sound a bit like tetra here. Which, isn't necessarily a bad thing. Especially if it can be made compatible with any standard tool type. Being able to add things to a botania or nature's aura tool, for example, would be very interesting.

**Comment by Mowmaster** [comment]
forgot to add this from my own discord, not sure if itll be part of the anvil or something else, or maybe nothing at all: https://minecraft.fandom.com/wiki/Attribute

**Comment by CoolFreeze23** [comment]
I think the 105 levels limit should be removed tbh
