### ISSUE TITLE
[Text Improvements] Spelling/Grammar fixes

### ISSUE THREAD

**Issue by Mowmaster** [Mowmaster/Pedestals#125]
"sorrounding pedestals" should be "surrounding pedestals"

**Comment by Rykzu** [comment]
"chat_sorround" should be "chat_surround".

**Comment by Rykzu** [comment]
"Pedestals can be Ppaced on all 6 sides" -> "Pedestals can be Placed on all 6 sides"

**Comment by Rykzu** [comment]
"Colored Pallet" -> "Colored Palette". "Color Pallet" -> "Color Palette"

**Comment by Rykzu** [comment]
Original:  "jei.pedestals.enderimport.desc": "The player who places the upgrade on pedestal, will assign it to their Ender Chest's inventory. This upgrade removes items from the pedestal and puts it in the Ender Chest. Due to the inconsistencies of Ender Magic, this upgrade only works when the player is in the same dimension."

Helps readability:  "jei.pedestals.enderimport.desc": "The player who places the upgrade on **a/the** pedestal, will **link** it to their Ender Chest's inventory. This upgrade removes items from the pedestal and puts it in the **linked Ender Chest's inventory.** Due to the inconsistencies of Ender Magic, this upgrade only works when the player is in the same dimension **as the pedestal.**"

**Comment by Mowmaster** [comment]
Closing all 1.16 issues, as I am no longer supporting this version of the game and 1.19+ is a full rewrite, I will however accept and merge any fixes folks make for this version.
