### ISSUE TITLE
pedestals FPS lag

### ISSUE THREAD

**Issue by bloodscon** [Mowmaster/Pedestals#131]
just been playing a bit of atm6 and had bad lag around my farm so decided to find where it was coming from so backed up my world and went into a creative world and discovered the pedestals seem to be quite heavy on FPS but it's not the bases that's the problem it's the upgrades themselves

No Pedestals

![2021-08-31_22 08 31](https://user-images.githubusercontent.com/50034844/131576207-d87ffdda-2ab5-4eab-a702-39addbfbe37d.png)

Pedestals only 

![2021-08-31_21 54 14](https://user-images.githubusercontent.com/50034844/131575768-d44d0dee-0b58-4536-ade1-59658e242827.png)

(capacity and the speed augments made no change)

Pedestal with upgrades at base lv

![2021-08-31_21 56 01](https://user-images.githubusercontent.com/50034844/131575907-578568e2-bd09-47de-9c97-f4751eec8007.png)

Pedestal with upgrades at tier 5 enchants

![2021-08-31_21 53 02](https://user-images.githubusercontent.com/50034844/131576034-b907db23-a397-47fa-9e18-d062ed27212c.png)

**Comment by Mowmaster** [comment]
Go place a wall of 144 item frames with that upgrade in it.
You should see a similar fps drop.
Upgrades are not part of the pedestals texture, its a displayed item similar to an item frame, and there's 4 sides to a pedestal to display that on.

Possible fixes on my end are, decrease how many sides it displays on, or perform some sort of magic to make minecraft render things better...
If you have any coder suggestions I'm all ears on this.

**Comment by Mowmaster** [comment]
Alright, not a 'fix' really, but an option for those who have serious fps lag when you have hundreds of pedestals in your base all within your view render area: https://github.com/Mowmaster/Pedestals/commit/ef73b8e30929d53991b6ef8d3ca61a98563288b2
- "Control"
![Render_Control](https://user-images.githubusercontent.com/10681506/141937334-385d2caf-19c7-42af-b755-909589016a11.png)
- No Item Render
![Render_NoItem](https://user-images.githubusercontent.com/10681506/141937365-86e000fb-0fbf-4772-bd29-ee271d90732e.png)
- No Upgrade Render (since there is 4 of them rendering each pedestal, this is 80% of the problem)
![Render_NoUpgrade](https://user-images.githubusercontent.com/10681506/141937499-80c35457-c208-4094-a4b2-5a30d80f23c0.png)
- No Item or Upgrade Rendering
![Render_None](https://user-images.githubusercontent.com/10681506/141937551-bcd7d405-645f-4116-bd49-4a8cfee4a997.png)

**Comment by SGZ-Creations** [comment]
Think #147 is simular to this tho deffently not sure.
