### ISSUE TITLE
Frequent superfluous chunk update 

### ISSUE THREAD

**Issue by sfPlayer1** [Mowmaster/Pedestals#15]
I've observed a `pedestals:pedestal/stone333` spamming chunk updates despite zero observable change. Actual cause is unknown, empty pedestals don't seem to do it. It may be related to ~1.5 SUpdateTileEntity per second. A breakpoint in `net.minecraft.client.renderer.WorldRenderer.markForRerender(int, int, int, boolean)` in an otherwise empty world during steady state should detect the exact cause.

https://files.player.to/tmp/pedestal-updates.png shows the problematic block.

**Comment by Mowmaster** [comment]
It appears the tile in question is probably updating the items in its stored inventory, the cobble generator upgrade looks to be enchanted which increases its cobble generated per operation and overall operation(update) speed. 
Simply right clicking on this pedestal with an Upgrade Tool item will give details on these rate changes.

I am aware some optimization is needed in the mod overall for chunk/block updates and ill be starting to clean those up a bit here soon, as i'm currently working on a new tile class rework already.

My recommendation for now (Until an update is ready to help resolve this) would be the user to enchant the upgrade with Capacity 5 (64 cobble generated) and NO or 1 level of Speed enchantments(Updates every 20/10 ticks), this will significantly reduce the number of updates happening.

**Comment by Mowmaster** [comment]
I have made some improvements to this in the recent version by not updating as many things, as often. but its still not perfect, and ill come back to make another pass at improvement on this later.

**Comment by desagas** [comment]
I am not sure if this is related or not, but this combination caused my ms to spike from 27 average to 53 on average.

In what you can see in my inventory, the fluid crafter has Capacity and Speed V, the extract has VII (apotheosis) and the import has IX (apotheosis).

Here is what happens:
1. Placing blocks the pedestals are interacting with adds nothing to TPS
![Screen Shot 2020-12-30 at 5 02 33 PM](https://user-images.githubusercontent.com/8404632/103387596-d786a080-4ac1-11eb-84a9-f57cf5352c58.png)

2. Placing pedestals adds nothing to TPS
![Screen Shot 2020-12-30 at 5 03 01 PM](https://user-images.githubusercontent.com/8404632/103387601-dbb2be00-4ac1-11eb-8367-ffd43d91328a.png)

3. Placing both Export and Import Upgrades add nothing to TPS
![Screen Shot 2020-12-30 at 5 04 54 PM](https://user-images.githubusercontent.com/8404632/103387605-df464500-4ac1-11eb-8a99-53e29449f8d8.png)

4. Adding the Fluid 3x3 Crafter, instantly spikes TPS
![Screen Shot 2020-12-30 at 5 05 30 PM](https://user-images.githubusercontent.com/8404632/103387609-e2413580-4ac1-11eb-9d71-6da9c75ce91f.png)


Unfortunately, this makes the mod unusable for anything but item transfer, which is still a good use for it.

**Comment by Mowmaster** [comment]
optimization is a constant struggle. this mod is only ~6 months old and i dont do this for a living, so itll take time, but it is constantly improving. update 0.8m+ is a fine example where ive reworked quite a few upgrades that used to be horrible for tps, and are now way better, still not perfect, but way better non the less

**Comment by desagas** [comment]
I looked very briefly at your code, it took me a minute, but it looks like you are checking to see if items exist / match before crafting, but, I couldn't see if you were checking to see if items were in the inventory or even if an inventory existed below BEFORE trying to match a recipe. While check this wont help with the TPS when reserved items are kept, it might help otherwise. As for reserved items, it might be useful to give the crafting upgrade a temporary NBT tag that states what is currently craftable, once found, like the teleport upgrade stores nbt for charges left.

In my example, your code has checked all 9 slots, and determined that 1234 6789 are stone, while 4 is a lava bucket, so, the code could add an nbt tag once the search has determined what we are crafting, and store that item ... or that recipe to prevent further useless searches. So, when items increase in the future, It doesn't have to search, then, you could add like a 5 second check or something like that to see if the contents of the inventory below have changed, as in, different itemStacks, not quantities, and then trigger a new search.

Anyways, just a suggestion. I might play around with it a bit, in a day or two, and see if I can learn a thing or two about what I just suggested.

Happy New Years

And, for just starting out, it is a pretty great mod!

**Comment by Mowmaster** [comment]
Closing all 1.16 issues, as I am no longer supporting this version of the game and 1.19+ is a full rewrite, I will however accept and merge any fixes folks make for this version.
