### ISSUE TITLE
[Suggestion] Remote Inventory Targeting for `ItemUpgradeImport`

### ISSUE THREAD

**Issue by Mowmaster** [Mowmaster/Pedestals#163]
Allow import/export (and maybe others) to use remote (below) inventories and maybe even multiple (using the revamped 'work areas' system)

**Comment by mfrankov** [comment]
I'll take a stab at this issue next -- specifically thinking of allowing `Work Card (Locations)` as the way to define the inventories. As random thoughts:
* Use `Work Card (Locations)`. I'm not opposed to maybe looking into `Work Card (Area)` in the future, but I think honestly that seems less useful for this particular case.
* Have this be controlled by an infusion, where the recipe is something like `Ender Pearl` + `Work Card (Locations)`? This should allow the `*upgradeHUD` to display if the work card is needed immediately when the upgrade is inserted, and also reduce the control of this behavior based purely on the existence of a card. Perhaps something like `Remote Inv. Targeting` (assuming it fits into character limits, this is close to `Entity Inv. Targeting` at least).
  * This does raise the fact that we probably need to make it clearer to people that you can't swap from an Import to Export and retain the infusions (even though they both support the same ones) as the NBT is cleared when that happens... unless we want to figure a way around that. 
* Would benefit if the behavior is to send until the total item (etc) capacity has been sent, rather than just sending to the first pedestal (especially given this could be done on all contained types). This does raise the question of whether supporting round-robin makes sense, but there's another issue there so for now can punt on that.

**Comment by mfrankov** [comment]
renaming and cutting a second issue for export (as I'm testing that and thus can mark it as resolved in the event we want to release this in separate updates / depending on how busy I am before I can get around to import).

**Comment by mfrankov** [comment]
Support in 1.19: https://github.com/Mowmaster/Pedestals/commit/8e30bfc9e24378dd8a9eecb286f768c82bf56ca4
Support in 1.20: https://github.com/Mowmaster/Pedestals/commit/5e3258c5608e1cf23db1af491b98ad22a71652b7

**Comment by mfrankov** [comment]
released...
1.19: https://www.curseforge.com/minecraft/mc-mods/pedestals/files/4687228
1.20: https://www.curseforge.com/minecraft/mc-mods/pedestals/files/4687522
