### ISSUE TITLE
bug: crafter cant craft 2 bows together

### ISSUE THREAD

**Issue by Mowmaster** [Mowmaster/Pedestals#187]

**Comment by mfrankov** [comment]
Source of the issue was that crafting two damaged and repairable items together returns a `net.minecraft.world.item.crafting.RepairItemRecipe` and not a `net.minecraft.world.item.crafting.ShapelessRecipe`/`net.minecraft.world.item.crafting.ShapedRecipe`.

`RepairItemRecipe` returns `ItemStack.EMPTY` for `getResultItem()` and instead requires calling `recipe.assemble(CraftingContainer container)` -- an easy enough fix.

**Comment by Mowmaster** [comment]
1.19 released in this version: https://github.com/Mowmaster/Pedestals/commit/1c83f5684a4a84458dbea05b8840644e52af1bbc
