### ISSUE TITLE
material gen bug

### ISSUE THREAD

**Issue by Mowmaster** [Mowmaster/Pedestals#223]
![image](https://github.com/Mowmaster/Pedestals/assets/10681506/481e4e9b-8e5f-48bb-98db-226219220d34)

**Comment by mfrankov** [comment]
This is due to the fact that the requirements are written using `MowLib`s `MowLibCompoundTagUtils`, which for `writeFluidStackToNBT` (code [here](https://github.com/Mowmaster/MowLib/blob/1.19/src/main/java/com/mowmaster/mowlib/MowLibUtils/MowLibCompoundTagUtils.java#L156-L164)) only updates the tag if the stack is non-empty:
```
    public static CompoundTag writeFluidStackToNBT(String ModID, @Nullable CompoundTag inputNBT, FluidStack fluidStack, String identifier) {
        CompoundTag compound = inputNBT != null ? inputNBT : new CompoundTag();
        if (fluidStack.isEmpty()) {
            return compound;
        } else {
            compound.put(ModID + identifier, fluidStack.writeToNBT(new CompoundTag()));
            return compound;
        }
    }
```

So we either need to fully invalidate the stored recipe NBT from the compound tag in `actionOnNeighborBelowChange`, or update MowLib to have it remove the identifier from the compound when the stack is empty (or move off of the MowLib helpers for now).

**Comment by mfrankov** [comment]
As a workaround if anyone else is experiencing the issue, removing the upgrade would be sufficient to resolve the requirements (as `actionOnRemovedFromPedestal` resets the cached recipe completely).

**Comment by mfrankov** [comment]
Resolved with https://github.com/Mowmaster/Pedestals/commit/47526395ae7aa6bb0ec0162732f15b54df4fedfe

**Comment by Mowmaster** [comment]
released in this version: https://github.com/Mowmaster/Pedestals/commit/1c83f5684a4a84458dbea05b8840644e52af1bbc
