### ISSUE TITLE
Material Generator only mining 1 block at a time after adding Speed Augments.

### ISSUE THREAD

**Issue by Furious1964** [Mowmaster/Pedestals#229]
Anyone know how to make the Material Generator of Pedestals go any faster? I've added Speed Augments and they're still mining 1 block at a time. Please help. Thanks.

**Comment by mfrankov** [comment]
`Augments` modify the pedestal itself (so a `Speed Augment` reduces the number of ticks required before a pedestal will attempt to transfer items to another pedestal).

In order to effect the actual `Upgrade`s placed on pedestal, you need to use an `Upgrade Modifier` (that's the name of the tab in JEI to look up recipes) which are added to an upgrade using the `Modification Infusion Upgrade`.

In the case of the Material Generator, you look through JEI to find the recipes and increase either:
* `Item Capacity` to increase the number of items mined each operation (at max you get 64 items generated for a single operation), or
* `Speed` to decrease the number of ticks between each operation (at max you generate however many items based on your item capacity [default 1] every tick).

If you're concerned about gameplay performance, `Item Capacity` has far less impact (it literally just multiplies the number of items you get at once, versus having to do all the work to determine what is mined far more frequently if you go the speed route).

**Comment by Furious1964** [comment]
Thank you for the info.
