### ISSUE TITLE
Bug: Output pedestal upgrade duplication

### ISSUE THREAD

**Issue by soulfoood** [Mowmaster/Pedestals#231]
I wanted to automate upgrading upgrades by using a block that would automatically right click to extract the upgraded upgrade (in my case, a material generator). I used a cyclic item user and had it right click every tick and it started spitting out an upgraded material generator (10/40) every tick. 
![2023-06-21_12 58 49](https://github.com/Mowmaster/Pedestals/assets/40434363/2a3aac74-438a-4cd2-9b3f-4033d7a9f9c1)

**Comment by mfrankov** [comment]
Sounds like this should have been handled by https://github.com/Mowmaster/Pedestals/issues/217 (which was tracked in the FTBSkies repo as https://github.com/FTBTeam/FTB-Modpack-Issues/issues/3319).

That made it's way out in Pedestals version 0.2.49, which was picked up in FTB Skies 1.2.0. Can you let me know what version of Pedestals you're running into this issue with?

**Comment by soulfoood** [comment]
pedestals-0.2.49.

**Comment by Mowmaster** [comment]
this appears to be a cyclic bug from a while ago
https://github.com/Lothrazar/Cyclic/issues/2220

as i stated in the FTB issue, cyclic doent stop its item user once the slot fills up, this is the fatal flaw that causes the issue (create deployer should in theory also have problems if its pedestals fault, but it doesnt because create prevents further action once its slots are filled in the deployer)
Regardless, i made some changes that will prevent this going forward (i installed cyclic in my dev enviro to make sure of this)
https://github.com/Mowmaster/Pedestals/commit/743824e3b8c67d0ba38fe055b40a336d4b94475c

**Comment by Mowmaster** [comment]
1.19 released in this version: https://github.com/Mowmaster/Pedestals/commit/1c83f5684a4a84458dbea05b8840644e52af1bbc

**Comment by Mowmaster** [comment]
1.20 fixed: https://github.com/Mowmaster/Pedestals/commit/55918833e4bb5dcbdaa35c038045c66df83659b5
