### ISSUE TITLE
Crash attacking upgrade with 0.8h

### ISSUE THREAD

**Issue by jinkhya** [Mowmaster/Pedestals#24]
Hello, 

A crash appeared with the update from 0.8g to 0.8h.
I'm using a pedestal with the attacking upgrade, a sword is also on top of it. As soon as I turned on my mobfarm and mobs started being killed by the pedestal it insta crashed the server. 
Here's the crashlog : https://gist.github.com/jinkhya/95789d8275c961f5a1f94554a32c1f1e

Thanks in advance :)

**Comment by Mowmaster** [comment]
i felt like i forgot something when i added new death messages, and it appears i did, thanks for catching this!
Fixed: https://github.com/Mowmaster/Pedestals/commit/b45c0a1c32e7604214f802d458df50486e4c0d7f
if you want a fixed build, i have one up on my discord, otherwise youll have to wait till the next uploaded update.
https://discordapp.com/channels/314719788351881218/725528892051554304/780950559724666940
