### ISSUE TITLE
suggestion - allow material generator to generate concrete

### ISSUE THREAD

**Issue by jlp1528** [Mowmaster/Pedestals#253]
Concrete is just a building block. The material generator generates (mostly) building materials. Therefore it should be capable of generating concrete.

**Comment by Mowmaster** [comment]
concrete is a crafted block crafted from sand, clay, and gravel, doused in water. 
Since you can already generate all those ingredients, and there is upgrades that allow you to automate it fully, i dont really see a reason to generate it. 

this of course doesn't mean pack makers cant add their own recipes to bypass this, but by default i dont plan to support this bypass of automation.
