### ISSUE TITLE
[1.16.4] Fluid Crafter - Not enough fluid to craft, but still crafts...

### ISSUE THREAD

**Issue by Mowmaster** [Mowmaster/Pedestals#28]
Since Industrial foregoing adds fluid milk, I tried crafting cake, it works, except when there is less than 3000mb of milk left it will still craft the cake, but also spit out a bucket for however many buckets of fluid the recipe was short of milk as well as delete the fluid crafting placeholder in those slots.

I would assume this would also happen in other recipes that require multiple buckets of the same fluid.

(Since im the dev, this is a note) : Probable fix would be to keep track of how many buckets of fluid have already been used when setting up the recipe, so if the estimated fluid needed is more than what is stored it'll prevent the recipe from crafting.
[Currently it just checks to see if there is at least 1 bucket of fluid in the pedestal every time the crafter sees a fluid crafting placeholder item, which is why this works fine for recipes with only 1 bucket of fluid]

**Comment by Mowmaster** [comment]
fixed: https://github.com/Mowmaster/Pedestals/commit/6e6b416909bb605ca117f7a45a5bcbc36d720680

**Comment by desagas** [comment]
Not exactly identical, but related, when crafting with fluids in the 3x3, with 1234 as stone, 5 as a bucket placeholder, and 6789 as stone, with lava coming from another pedestal with the fluid import upgrade, in ALM6 1.3.7, P0.8I, to craft basalt, with the crafting upgrade enchanted with Capacity and Speed V, it crafts 64 items, 8 crafts, which it should (8 per craft, maxing at 64), but, it only uses one bucket of lava for the operation of 8 crafts, rather than 1 bucket per craft. It is a nice bug, but a bug none the less.

**Comment by Mowmaster** [comment]
https://github.com/Mowmaster/Pedestals/commit/186556c62e9f5e3abf1fa9bc9f4b458f921390a0
