### ISSUE TITLE
[Feature Request] Let pedestals be used as inventories for other pedestals

### ISSUE THREAD

**Issue by KrAzYGEEK32** [Mowmaster/Pedestals#30]
i don't know if this would be complicated to implement but this would make setting up processing chains so much more easier, without having to setup bulky inventories below and import into them. if you didnt get my dumb explanation ill be happy to provide a visual one, love the mod a lot :heart:

**Comment by Mowmaster** [comment]
Back in 1.12.2 pedestals wernt actually true inventories and so trying to use them as such would crash the game.
Now in 1.16 they technically are, but i still have mild PTSD when i think about adding this back in, especially since its hardcoded everywhere in the mod to ignore any other pedestal when doing a lot of tasks.

Bottom line, Could it be done? Yes. 
Will I do it in 1.16? Not planned.
Will I consider it for 1.17+? Yes.

**Comment by Mowmaster** [comment]
If you really wanted to, hoppers can pull out of pedestals, and are inventories themselves.

**Comment by KrAzYGEEK32** [comment]
Yea fair, :) . I thought that would work already and tried it and became sad lol, that's why I made the request. Although I never thought about hoppers XD, dumb me. Ty for clarifying anyway
