### ISSUE TITLE
Can't anvil combine anymore.

### ISSUE THREAD

**Issue by spdkils** [Mowmaster/Pedestals#45]
In .8r I'm unable to combine any enchants anymore.

I've been looking and looking for configs, what changed, if I need to upgrade again, not sure. It used to just work... Now it will not combine items and merge their enchants.

Say I have a looting III sword and a looting III sword (two different types). I used to be able to combine to looting IV, and keep the type of the center sword. Now... not so much.

**Comment by Mowmaster** [comment]
https://youtu.be/n0xMD9qBm5E

this video was made with 0.8r hotfix 4 
basically looting cost 8x due to being a very rare enchant
so if you have any other enchants on the sword the cost to combine gets expensive fast.
combining just 2x looting 4 books cost ((4+1)*8)*2 levels now. ~80 levels if you also had unbreaking and sharpness on the sword, theres a good chance you might be exceeding the 105 level cap on the anvil.
