### ISSUE TITLE
Enhancement: Let the shearing upgrade shear from bee hives

### ISSUE THREAD

**Issue by Shindur** [Mowmaster/Pedestals#5]
As the title says, the shearing upgrade could also shear MC bee hives and Productive Bees hives/advanced hives. Would be interesting :)

**Comment by Mowmaster** [comment]
the current shearing upgrade only works on entities in the world, having it target blocks could be done, but is outside what i intended for that upgrade.

Using a dispenser, you can shear and bottle honey already, I dont really see a need for me to add this functionality in since vanilla has already made a way to automate it. but ill add it to my trello as a consideration if i get a ton of requests for it.
