### ISSUE TITLE
No Documentation on A Few Pedestal Upgrades

### ISSUE THREAD

**Issue by DizzyDJW** [Mowmaster/Pedestals#60]
The two I've noticed are: Fluid to Exp Converter and Energy Generator. I'm sure there are more but it just so happened that the two I found most interesting had no documentation and nothing "straighforward" worked with them.

I'm assuming you fill it with water, lava, milk, etc... and it converts it into XP? Filling the F-to-Xp with liquids off all kinds created no fluids, neither from the top nor bottom.

My assumption here is that burnables placed atop it will cause it to burn them into power? Placing Coal, Coal Blocks, Logs, etc... Didn't seem to "Activate" the Energy Generator, even though it sounds like it would take Coal or Burnables and create power, it does not...

If I'm wrong about these two, please feel free to correct me.

**Comment by Mowmaster** [comment]
![image](https://user-images.githubusercontent.com/10681506/112782714-487f1b00-9013-11eb-8cc4-032802b732d3.png)
![image](https://user-images.githubusercontent.com/10681506/112782738-5634a080-9013-11eb-9f92-e17155694688.png)

I can add a jei description to the fluid to xp converter, but otherwise i dont see this as an issue.
Proper Documentation will get done eventually, its just, either i do documentation, or fix issues and add new/improve content.
Considering all the requests ill probably make the 0.8t update a documentation one. (0.8s is the next update)

**Comment by DizzyDJW** [comment]
Didn't think to check JEI uses. I looked all through the Patchouli book and Wiki but nothing on those specific two... Thanks!
