### ISSUE TITLE
item filter doesn't accept modded items

### ISSUE THREAD

**Issue by theitalianweeb** [Mowmaster/Pedestals#63]
I was trying to make an item filter with bitumen, from thermal series, and it doesn't work. I assume the recipe for the filter is the item itself and the pedestal upgrade

**Comment by Mowmaster** [comment]
Latest version just came out (0.8s) Read JEI information tab on the Filter Tool for how they work now. OR wait a bit and ill have a video uploaded explaining the new filter system.

**Comment by Mowmaster** [comment]
https://www.youtube.com/watch?v=N3Doz6OKjmY&t=13s
^Video explaining deprecated upgrades, aka now unused ones. Since your assuming the recipe, im guessing you on the new version with the old deprecated upgrades that have no recipes.
Again, ill have a filter video out later, got slow as f internet out in the boonies

**Comment by Mowmaster** [comment]
started the upload, this should be the link explaining how filters work once its done uploading in like 5 hours... https://youtu.be/azaeIA8UjiQ
