### ISSUE TITLE
Unable to remove items from pedestals in creative

### ISSUE THREAD

**Issue by MuteTiefling** [Mowmaster/Pedestals#72]
Version: pedestals-0.8s_hotfix_1

`- You can retrieve 1 item from a pedestal with a Left-Click`

In Creative, this just breaks the pedestal :( Which gets me the items, but also means I have to set things back up..

**Comment by Mowmaster** [comment]
Yeah you can hot swap with f3+f4 to survival and do it fine, that's what I've been doing myself, not sure how to handle creative mode honestly

**Comment by MuteTiefling** [comment]
Hrm, yeah might be worth a look at how Mek or Storage Drawers handle this, since both use a left click to extract but do so correctly in Creative mode too

**Comment by Mowmaster** [comment]
https://github.com/Mowmaster/Pedestals/commit/2bcd7da83ffae3479b9c4ef16fd00948b7e87980

both other mods use the fact you can only pull from the front face of their block, pedestals doesnt have this luxury, so i made it require the dev tool in your inv when in creative to break pedestals. Will have to do for now, since i dont have a better way to do this really...
Maybe if i ever figure out special key bind presses or something
