### ISSUE TITLE
Compacting 3x3 upgrade seems to cause a tick hang for around 70 seconds causing servers to restart / crash.

### ISSUE THREAD

**Issue by MsVoxxie** [Mowmaster/Pedestals#79]
[Using This setup](https://user-images.githubusercontent.com/10318911/115980891-14d5d900-a55e-11eb-8c58-08f2cc55a4f7.png) leads to a few proper functions, usually the fifth operation will hang indefinitely causing a Watchdog crash, when used. otherwise the server never recovers.

Alternatively, this can be triggered ahead of time by sorting the inventory with Inventory Tweaks, May be a fault of checking for things to compact which are then moved?

[Screenshot of Diamond Chest contents](https://share.voxxie.me/i/2021-04-25_00.43.10.png)
[My Mod List](https://share.voxxie.me/i/2021-04-25_00.39.24.html)
[Latest Crash Log](https://share.voxxie.me/i/2021-04-25_00.39.04.txt)

**Comment by Mowmaster** [comment]
Known issue, generally happens with an inventory that has a shifting inventory, as on a block update change it will update every stack in the inventory to its 'memory' and recalculate the recipes in its 'memory'.

Any mod that sorts stacks in an inventory, depending on how the mod does it, can be super bad, and this is only made worse by a larger inventory. 

My recommendation, dont auto sort that inventory, set it up with automation. OR if you have storage drawers, Set it up on a controler. lock the drawers with the items being compressed and it runs quite well then.

Currently testing the 'Smart' Crafter to see if this can be completely replaced by that. So no current 'fix' is planned, as this will probably be removed in the future. 
Alt solution, switch to using the smart crafter, or even the normal crafter can work, since your probably using way to big of an inventory to begin with.

**Comment by Mowmaster** [comment]
didnt mean to close this yet...

**Comment by MsVoxxie** [comment]
I had a feeling it was as such, Appreciate the information and I'm looking forward to future updates, for now ill look into doing the drawers method you mentioned as that slipped my mind entirely. Thanks!

**Comment by Mowmaster** [comment]
Closing all 1.16 issues, as I am no longer supporting this version of the game and 1.19+ is a full rewrite, I will however accept and merge any fixes folks make for this version.
